### ISSUE TITLE
matomo.php is always appended to trackerUrl 

### ISSUE THREAD

**Issue by timaebi** [EmmanuelRoux/ngx-matomo#24]
First of all I want to thank you for your great work. 👏🏻

Unfortunately, we can not use this plugin in our project at the time because of a tiny detail. In the `MatomoInitializerService` the `TRACKER_SUFFIX` `matomo.php` is always appended to the configured `trackerUrl`. However, in our setup we use a different path for the tracker endpoint which does not end in `matomo.php`. For  me it seems unintuitive to automatically append a suffix to the configured `trackerUrl`s.

Could this suffix be removed? Maybe not as this is a backward incompatible change and would lead to a new major version.

Or could we add an optional configuration option to avoid adding this suffix? This would solve our issue in backward compatible manner.

If you want I could possibly provide a PR for this. @EmmanuelRoux, would you accept such a PR?

(I know we could manually initialise the tracker but we prefer to use the auto mode.)

**Comment by EmmanuelRoux** [comment]
Hi @timaebi, thank you

You are right, `matomo.php` is appended to the provided tracker url because it is Matomo's default and very common configuration.

You can of course provide a PR to make this lib fit your needs.
In this case, I think it would be better to provide a backward compatible solution, for example an additional config option `trackerUrlSuffix` (with `matomo.php` as default value). But feel free to suggest whatever you want!

Also, it doesn't seem to be the problem you're describing here, but remember that you can customize the `scriptUrl` from which the JS tracking code is obtained.

**Comment by traycold** [comment]
would it be possible to merge this fix on branch `1.x` ? I need it on a project using Angular 10

**Comment by EmmanuelRoux** [comment]
Hi @traycold, do you think you can provide a PR please? 

You may cherry-pick bd93470e478e4e90d15ded5f7c15e981de481cd8
