### ISSUE TITLE
Application freezes sometimes

### ISSUE THREAD

**Issue by VincentFraboulet123** [EmmanuelRoux/ngx-matomo#60]
Bonjour Emmanuel,

Dans le cadre d'un projet, j'ai dû intégrer Matomo afin de faire du tracking basique.
J'utilise la version 3.2.0 du ngx-matomo/router (donc la dernière version).

Depuis la mise en place du module, sur certaines actions, j'ai un freeze complet de mon application. Je dois fermer l'onglet et en ouvrir un nouveau. Ce problème est reproduit sur plusieurs navigateurs (FF, Chrome) et par plusieurs personnes sur plusieurs environnements.

C'est un problème qui arrive pendant une navigation (changement de page), à chaque fois depuis les mêmes pages, vers n'importe laquelle.

Lorsque je passe le paramètre "disabled" à true dans le MatomoConfiguration, je n'ai plus de problème (mais plus de tracking non plus). Dès que je le réactive, le problème apparait.

Avez-vous des retours quant à ce problème?

Merci d'avance

**Comment by EmmanuelRoux** [comment]
Bonjour @VincentFraboulet123 

>  sur certaines actions

Lesquelles ? Dans quel contexte ? Arrivez-vous à identifier l'instruction qui provoque le blocage ?

Pouvez-vous svp reproduire le problème sur un environnement minimal (type [Stackblitz](https://stackblitz.com/)) afin d'identifier l'origine

**Comment by Arrakis-Lux** [comment]
Hello there ! 
I'm a coworker of @VincentFraboulet123 and I have been investigating this issue for the past day or so.

I am sad to report that I haven't been able to identify the root cause of this issue :/ 
However, I did find something that fixes it. 

I was playing around with a smaller version of your matomo-router.service.ts and identified that it was the call to `this.tracker.trackPageView()` that was causing the freezes.
And I figured out that it was probably conflicting somehow with something within the angular internals (digest cycle or maybe change detection ? I'm not sure how to investigate that ...). And with that in mind, I tried running the function outside angular and asynchronically : 

```ts
this.router.events
      .pipe(
        // Take only NavigationEnd events
        filter(isNavigationEnd),
        distinctUntilKeyChanged('urlAfterRedirects')
      .subscribe((event) => {
        this.ngZone.runOutsideAngular((event) => setTimeout(() => {
            this.tracker.trackPageView(this.titleService.getTitle())
        }, 0))});
```
That ended up fixing the issue for us !

While looking around for clues i stumbled upon a few other people having the same kind of issues ([here](https://forum.matomo.org/t/ui-freezes-since-ngx-matomo-is-added/43328) or [here](https://github.com/Arnaud73/ngx-matomo/issues/37)) so I don't think the issue lies in your package but within matomo itself.

With all that said. For now we'll fork the repo in order to include this fix and i will submit a PR for you to review if you'd want to integrate it (and maybe another not linked to this issue :D).

**Comment by EmmanuelRoux** [comment]
Hi @Arrakis-Lux 

Thank you very much for the explanation. I also have been told by some people of _freezing_ problems with Matomo, but never had enough time to deeply investigate...

Have you tried __without__ `setTimeout` (only with `runOutsideAngular`)? 
I'm wondering why `setTimeout` would solve anything, because `NgxMatomoRouterModule` (which I assume you're using) is already applying a `delay` of 0ms by default, making the call asynchronous (unless you explicitly changed the `delay` option to `-1`).

__Could you please try again after removing `setTimeout` and moving `runOutsideAngular` call into `MatomoTracker` service (by applying the patch below), and let me know?__

After that, a PR would of course be very much appreciated (imho, we should include this fix as an opt-in config option to be 100% sure not to break anything in existing applications. We could discuss that later in the PR).

_____

```diff
Index: projects/tracker/src/lib/matomo-tracker.service.ts
<+>UTF-8
===================================================================
diff --git a/projects/tracker/src/lib/matomo-tracker.service.ts b/projects/tracker/src/lib/matomo-tracker.service.ts
--- a/projects/tracker/src/lib/matomo-tracker.service.ts	(revision fcdafad2114c0e09aa6bdc8b96cdfc91ea477010)
+++ b/projects/tracker/src/lib/matomo-tracker.service.ts	(date 1669300941200)
@@ -1,5 +1,5 @@
 import { isPlatformBrowser } from '@angular/common';
-import { Injectable, PLATFORM_ID } from '@angular/core';
+import { Injectable, NgZone, PLATFORM_ID } from '@angular/core';
 import { INTERNAL_MATOMO_CONFIGURATION, InternalMatomoConfiguration } from './configuration';
 import { initializeMatomoHolder, MatomoHolder } from './holder';
 import { Getters, RequireAtLeastOne } from './types';
@@ -103,17 +103,18 @@
 
 export function createMatomoTracker(
   config: InternalMatomoConfiguration,
-  platformId: Object
+  platformId: Object,
+  ngZone: NgZone
 ): MatomoTracker {
   return config.disabled || !isPlatformBrowser(platformId)
     ? new NoopMatomoTracker()
-    : new StandardMatomoTracker();
+    : new StandardMatomoTracker(ngZone);
 }
 
 @Injectable({
   providedIn: 'root',
   useFactory: createMatomoTracker,
-  deps: [INTERNAL_MATOMO_CONFIGURATION, PLATFORM_ID],
+  deps: [INTERNAL_MATOMO_CONFIGURATION, PLATFORM_ID, NgZone],
 })
 export abstract class MatomoTracker {
   /**
@@ -1354,7 +1355,7 @@
 }
 
 export class StandardMatomoTracker extends MatomoTracker {
-  constructor() {
+  constructor(private readonly ngZone: NgZone) {
     super();
     initializeMatomoHolder();
   }
@@ -1370,7 +1371,9 @@
   }
 
   protected push(args: unknown[]): void {
-    window._paq.push(trimTrailingUndefinedElements(args));
+    this.ngZone.runOutsideAngular(() => {
+      window._paq.push(trimTrailingUndefinedElements(args));
+    });
   }
 }
 ```

**Comment by Arrakis-Lux** [comment]
I'll try that !

**Comment by Arrakis-Lux** [comment]
So ! 

Can confirm the patch fixes it ! 

I'll be working on that PR and will make sure it's an opt-in (this is a great idea i agree !)

**Comment by EmmanuelRoux** [comment]
Great! Don't hesitate to open a PR even if it's work in progress, so we can discuss about it

**Comment by Mikastark** [comment]
I had the same issue as the author, the run outside angular zone saved me. So thank you ;)
