### ISSUE TITLE
Angular 17 compatability

### ISSUE THREAD

**Issue by erwindemoel** [EmmanuelRoux/ngx-matomo#76]
Hi, we're very happily using your @ngx-matomo/router and @ngx-matomo/tracker. However it doesn't work on the latest version of Angular 17. Could you please update the project so we can keep using it?

**Comment by EmmanuelRoux** [comment]
Hi @erwindemoel 

Thank you for using this project!
__Good news is it’s already compatible with Angular 17!__

As stated [at the top of README](https://github.com/EmmanuelRoux/ngx-matomo/blob/main/README.md), it has been renamed since version 5 (and Angular 15/16).
__It is now distributed as a single package named `ngx-matomo-client`__, and you can easily migrate to this new package. 

Basically, you just have to run `ng add ngx-matomo-client`.

This will install new package and remove old ones, as well as migrate all typescript imports in your code. See [full instructions in README](https://github.com/EmmanuelRoux/ngx-matomo/blob/main/README.md#migration-from-ngx-matomotracker-and-ngx-matomorouter-version--4).

Please let me know if you have any problem doing this migration, I would be happy to help.

**Comment by EmmanuelRoux** [comment]
Hi @erwindemoel, is your issue solved?

**Comment by erwindemoel** [comment]
Yes, thanks!
